DECLARE_POINTERS(IDataModel);
DECLARE_POINTERS(IController);
DECLARE_POINTERS(IView);
DECLARE_POINTERS(IListener);


DECLARE_POINTERS(IServer);
DECLARE_POINTERS(IServerController);
DECLARE_POINTERS(IServerView);

DECLARE_POINTERS(IClient);
DECLARE_POINTERS(IClientController);
DECLARE_POINTERS(IClientView);
DECLARE_POINTERS(IClientBuilder);
DECLARE_POINTERS(IClientBuildersProvider);

DECLARE_POINTERS(IClientServiceConnection);
DECLARE_POINTERS(IClientService);
DECLARE_POINTERS(IClientServiceFactory);