DECLARE_POINTERS(IDataModel);
DECLARE_POINTERS(IController);
DECLARE_POINTERS(IView);
DECLARE_POINTERS(IListener);


DECLARE_POINTERS(IServer);

DECLARE_POINTERS(IClient);
DECLARE_POINTERS(IClientController);
DECLARE_POINTERS(IClientView);